- 0  # Invisibles
- 1  # NUbots
- 2  # Bold Hearts
- 7  # RoboFEI
- 8  # WF Wolves
- 9  # ITAndroids
- 10  # UTRA Robosoccer
- 11  # Rhoban
- 12  # TH-MOS
- 13  # Blenders FC
- 14  # Boosted HTWK
- 15  # PMec Humanoid
- 16  # PUMAS
- 17  # ZJUDancer
