- 0  # Invisibles
- 1  # NUbots
- 2  # Bold Hearts
- 7  # RoboFEI
- 8  # WF Wolves
- 9  # ITAndroids
- 10  # UTRA Robosoccer
- 11  # Rhoban
- 12  # TH-MOS
- 15  # ZJUDancer
- 16  # Blenders FC
- 17  # Boosted HTWK
- 18  # PMec Humanoid
- 19  # PUMAS
