- 0  # Invisibles
- 1  # NUbots
- 2  # Bold Hearts
- 3  # CIT Brains
- 4  # RO:BIT
- 5  # Barelang FC
- 6  # Bit Bots
- 7  # RoboFEI
- 8  # WF Wolves
- 9  # ITAndroids
- 10  # UTRA Robosoccer
- 11  # Rhoban
- 12  # TH-MOS
- 13  # Eepis Robot Soccer
- 14  # MRL-HSL
- 15  # ZJUNlict
